version: '3'
services:

  icandid_collector_dev:
    image: icandid_collector_dev
    build: 
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "cd /app
             tail -f /dev/null"
    networks: 
      - data_network
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ../../iCANDID/records:/records
      - ../../iCANDID/records_test:/records_test
      - ../../iCANDID/source_records:/source_records
      - ../../iCANDID/icandid_collector/logs:/app/logs
      - ./tom_vanmechelen/data_collector:/app/data_collector

  icandid_collector:
    build: 
      context: ./
      dockerfile: Dockerfile    
    networks:
      - data_network
    volumes:
      - ./config:/app/config
      - ../../iCANDID/records:/records
      - ../../iCANDID/source_records:/source_records
      - ../../iCANDID/icandid_collector/logs:/app/logs


networks:
  data_network:
    driver: bridge
