version: '3'
services:

  data_collector_dev:
    image: data_collector_dev
    build: 
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "cd /app
             tail -f /dev/null"
    networks: 
      - data_network
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ../records:/records
      - ../records_test:/records_test
      - ../source_records:/source_records
      - ./logs:/app/logs


networks:
  data_network:
    driver: bridge
